#!/usr/bin/env python3
"""Reproduce the paper's Zip-NeRF frontier, the RASS-48/96 export audits, and RASS-96 itself.

Recomputes everything from the released logs and compares the frontier with
the packaged results/audit_frontier.csv.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

from compute_audit import export_subset, fidelity_event, frontier, load_population, load_settings


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."), help="Artifact root.")
    args = parser.parse_args()
    root = args.root.resolve()

    settings = load_settings(root / "configs/audit_settings.yaml")
    df = load_population(settings)
    packaged = pd.read_csv(root / "results/audit_frontier.csv")
    rows = frontier(df, packaged["budget_scenes"].tolist(), settings)

    ok = True
    print("budget  n_pass  LCB     packaged")
    for r, (_, p) in zip(rows, packaged.iterrows()):
        same = r["n_pass"] == p["n_pass"]
        ok &= same
        print(f"{r['budget_scenes']:6d}  {r['n_pass']:6d}  {r['wilson_lcb']:.4f}  {p['n_pass']} {'ok' if same else 'MISMATCH'}")
    for name in ("rass48", "rass96"):
        ids = [s.strip() for s in (root / settings["scene_lists"][name]).read_text().splitlines() if s.strip()]
        ev = fidelity_event(df, ids, settings["thresholds"])
        print(f"{name}: {'PASS' if ev['joint_pass'] else 'FAIL'} | gaps PSNR {ev['psnr_gap']:+.4f} SSIM {ev['ssim_gap']:+.4f} "
              f"LPIPS {ev['lpips_gap']:+.4f} | max KS {ev['max_ks']:.4f}")
    rass96 = {s.strip() for s in (root / settings["scene_lists"]["rass96"]).read_text().splitlines() if s.strip()}
    regenerated = set(export_subset(df, 96, settings)) == rass96
    ok &= regenerated
    print(f"rass96 regenerated by the export rule: {regenerated}")
    print("rass48 is the recommended subset of the selection-time sweep; see rebuttal/selection_artifacts/")
    print("frontier reproduced" if ok else "frontier MISMATCH")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
